using 'main.bicep'

param environmentName = 'useracceptance'
param location = 'westeurope'
param functionAppRuntime = 'custom'
param functionAppRuntimeVersion = '1.0'
param resourceGroupName = 'bluegreen-deployment'
param functionPlanName = 'flexplan-useracceptance'
param functionAppName = 'flexfuncuseracceptance'
param storageAccountName = 'flexconsumptionstorag'
param apimServiceName = 'solarapimuat'
param apimResourceGroupName = 'api-management-demo'
